name: GKersz
favicon: null
layout_spectrum: 0.3895
typography_spectrum: 0.06106
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Gaja Kersz Contemporary Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0f0714'
    - '#4e7964'
    - '#3b4e57'
    - '#522f1b'
    - '#8e6768'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
