name: GKersz
favicon: null
layout_spectrum: 0.07459
typography_spectrum: 0.06106
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Gaja Kersz Contemporary Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1e2024'
    - '#d9ba92'
    - '#f1dbc2'
    - '#7b7a78'
    - '#453e3a'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
