collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.1869773
color:
  saturation: 0.458184
  brandStrength: 0.7357303
  lightness: 0.1212664
  brandColors:
    - '#060606'
    - '#FFFFFF'
    - '#84817A'
    - '#DCD5CB'
    - '#5D5E59'
  rhythmicContrast: 0.4772998
layout_spectrum: 0
name: GKersz
