collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.458184
  brandStrength: 0
  lightness: 0.1212664
  brandColors:
    - '#32332E'
    - '#BDBBAE'
    - '#909696'
    - '#FFFFFF'
    - '#FE9449'
  rhythmicContrast: 0.4772998
typography_spectrum: 0.1869773
layout_spectrum: 0.4426523
name: GKersz
