collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.1571087
  brandStrength: 0.4808841
  lightness: 0.7867383
  brandColors:
    - '#FFFFFF'
    - '#171B1E'
    - '#90C4F7'
    - '#C7907B'
    - '#374B56'
  rhythmicContrast: 0.8679808
typography_spectrum: 0.1869773
layout_spectrum: 0.4426523
name: GKersz
