layout_spectrum: 0
typography_spectrum: 0.1869773
color:
  saturation: 0.01493427
  lightness: 0
  brandStrength: 0.7357303
  brandColors:
    - '#060606'
    - '#FFFFFF'
    - '#84817A'
    - '#DCD5CB'
    - '#5D5E59'
  rhythmicContrast: 0.08900837
name: GKersz
